name: Saucedemo-web-automation-playwright-test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: 'true'
          BASE_URL: 'https://www.saucedemo.com'  # Explicit URL
          # DEBUG: 'pw:api'  # Uncomment untuk debug detail
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-report
          path: |
            playwright-report/
            test-results/
            test-results.json
          retention-days: 30
      
      - name: Configure GitHub pages
        if: always()
        uses: actions/configure-pages@v5
        with:
          enablement: true
      
      - name: Upload Artifact to GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report
      
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4
